include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    - prefer_single_quotes: false  # Uncomment to enable the `prefer_single_quotes` rule
    - use_super_parameters: true
    - prefer_double_quotes: true
    - cancel_subscriptions
    - always_use_package_imports
    - always_declare_return_types
    - unawaited_futures
    - unused_local_variable